# Generated by Django 4.1.1 on 2022-12-31 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Payer_Name', models.CharField(max_length=200, null=True)),
                ('Payer_Phone_no', models.IntegerField(null=True)),
                ('Payer_Email', models.EmailField(max_length=254, null=True)),
                ('Service', models.CharField(max_length=200, null=True)),
                ('Amount', models.IntegerField(null=True)),
                ('select', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
