# Generated by Django 4.1.1 on 2022-12-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='Service',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
