# Generated by Django 4.1.1 on 2022-12-31 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('Bank', models.CharField(max_length=200, null=True)),
                ('Account', models.IntegerField(null=True)),
                ('logo', models.ImageField(default='default.png', null=True, upload_to='profile_images')),
                ('licenses', models.ImageField(default='default.png', null=True, upload_to='profile_images')),
                ('cac', models.ImageField(default='default.png', null=True, upload_to='profile_images')),
                ('staff', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
