# Generated by Django 4.1.1 on 2022-11-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Account',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Bank',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
