# Generated by Django 4.1.1 on 2022-12-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_user_profile_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Account',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
