# Generated by Django 4.1.1 on 2022-12-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_account_alter_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='school',
            new_name='school_name',
        ),
    ]
